version: '3.7'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    ports:
        - 8200:8200

  database:
    image: mysql:latest
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=app
      - MYSQL_USER=vault
      - MYSQL_PASSWORD=${MYSQL_VAULT_PASSWORD}
    ports:
      - 3306:3306

  app:
    image: php:7.4-apache-bullseye
    container_name: app
    ports:
      - 80:80
      - 443:443
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ./app:/var/www/html

